/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.pro.byjader;

import javax.swing.JOptionPane;

/**
 *
 * @author kill
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }
    
  String textoA = "0";
  String textoB = "0";
  String operacao = "0";
  String conc = "";
  //Double total = 0.0;
  Double total1 = 0.0;
   
    
    public void recebeVal(String val) {
        

        if ( (textoA).equals("0") && (operacao).equals("0") ) {
            textoA = val;
            resultadoText.setText(val);
        } else if (!(textoA).equals("0") && (operacao).equals("0")) {
            JOptionPane.showMessageDialog(null, "Para executar uma operacao, escolha o operador.");
        } 
        else if ((textoA).equals("0") && !(operacao).equals("0")) {
            JOptionPane.showMessageDialog(null, "Operacao invalida, inicie escolhendo numeros.");
            operacao = "0";
            
        }
        
        else if(!(textoA).equals("0") && !(operacao).equals("0")){
            textoB = val;
            exibeResultado();
     
        }
    }

    private void exibeResultado() {
        double a = Double.parseDouble(textoA);
        double b = Double.parseDouble(textoB);
        String conc10 = resultadoText.getText();
        switch (operacao) {
            case "+":
                total1 = a + b;
                operacao = "0";
            
                break;
            case "-":
                total1 = a - b;
                operacao = "0";
                break;
            case "/":
                total1 = a / b;
                operacao = "0";
                break;
            case "*":
                total1 = a * b;
                operacao = "0";
                break;
        }
        System.out.println(total1);      
        //total += total1;
        textoA = String.valueOf(total1);
        //String numero = String.valueOf(total1);
        resultAtualText.setText(textoA);
             
        resultadoText.setText(conc10+textoB);
        operacao = "0";
    }
    
    public static boolean Numerico(String str)  
    {  
      try  
      {  
        double d = Double.parseDouble(str);  
      }  
      catch(NumberFormatException nfe)  
      {  
        return false;  
      }  
      return true;  
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        maisButton = new javax.swing.JButton();
        menosButton = new javax.swing.JButton();
        vezesButton = new javax.swing.JButton();
        dividirButton = new javax.swing.JButton();
        zerarButton = new javax.swing.JButton();
        igualButton = new javax.swing.JButton();
        umButton = new javax.swing.JButton();
        doisButton = new javax.swing.JButton();
        tresButton = new javax.swing.JButton();
        quatroButton = new javax.swing.JButton();
        cincoButton = new javax.swing.JButton();
        seisButton = new javax.swing.JButton();
        seteButton = new javax.swing.JButton();
        oitoButton = new javax.swing.JButton();
        noveButton = new javax.swing.JButton();
        resultadoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        floatText = new javax.swing.JTextPane();
        okButton = new javax.swing.JButton();
        resultAtualText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        maisButton.setBackground(new java.awt.Color(20, 147, 228));
        maisButton.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        maisButton.setForeground(new java.awt.Color(254, 254, 254));
        maisButton.setText("+");
        maisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisButtonActionPerformed(evt);
            }
        });

        menosButton.setBackground(new java.awt.Color(20, 147, 228));
        menosButton.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        menosButton.setForeground(new java.awt.Color(253, 251, 251));
        menosButton.setText("-");
        menosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosButtonActionPerformed(evt);
            }
        });

        vezesButton.setBackground(new java.awt.Color(20, 147, 228));
        vezesButton.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        vezesButton.setForeground(new java.awt.Color(255, 245, 245));
        vezesButton.setText("*");
        vezesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezesButtonActionPerformed(evt);
            }
        });

        dividirButton.setBackground(new java.awt.Color(20, 147, 228));
        dividirButton.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        dividirButton.setForeground(new java.awt.Color(254, 254, 254));
        dividirButton.setText("/");
        dividirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirButtonActionPerformed(evt);
            }
        });

        zerarButton.setBackground(new java.awt.Color(20, 147, 228));
        zerarButton.setForeground(new java.awt.Color(254, 254, 254));
        zerarButton.setText("Zerar");
        zerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerarButtonActionPerformed(evt);
            }
        });

        igualButton.setBackground(new java.awt.Color(20, 147, 228));
        igualButton.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        igualButton.setForeground(new java.awt.Color(254, 247, 247));
        igualButton.setText("=");
        igualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualButtonActionPerformed(evt);
            }
        });

        umButton.setBackground(new java.awt.Color(20, 147, 228));
        umButton.setText("1");
        umButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umButtonActionPerformed(evt);
            }
        });

        doisButton.setBackground(new java.awt.Color(20, 147, 228));
        doisButton.setText("2");
        doisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisButtonActionPerformed(evt);
            }
        });

        tresButton.setBackground(new java.awt.Color(20, 147, 228));
        tresButton.setText("3");
        tresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresButtonActionPerformed(evt);
            }
        });

        quatroButton.setBackground(new java.awt.Color(20, 147, 228));
        quatroButton.setText("4");
        quatroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroButtonActionPerformed(evt);
            }
        });

        cincoButton.setBackground(new java.awt.Color(20, 147, 228));
        cincoButton.setText("5");
        cincoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoButtonActionPerformed(evt);
            }
        });

        seisButton.setBackground(new java.awt.Color(20, 147, 228));
        seisButton.setText("6");
        seisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisButtonActionPerformed(evt);
            }
        });

        seteButton.setBackground(new java.awt.Color(20, 147, 228));
        seteButton.setText("7");
        seteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteButtonActionPerformed(evt);
            }
        });

        oitoButton.setBackground(new java.awt.Color(20, 147, 228));
        oitoButton.setText("8");
        oitoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoButtonActionPerformed(evt);
            }
        });

        noveButton.setBackground(new java.awt.Color(20, 147, 228));
        noveButton.setText("9");
        noveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveButtonActionPerformed(evt);
            }
        });

        resultadoText.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        resultadoText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultadoText.setText("0");
        resultadoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTextActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(floatText);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        resultAtualText.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        resultAtualText.setText("#");
        resultAtualText.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(255, 229, 229));
        jLabel1.setText("Float Valor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(menosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vezesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dividirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultAtualText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(igualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zerarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resultadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(umButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oitoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(umButton)
                        .addComponent(doisButton)
                        .addComponent(tresButton)
                        .addComponent(quatroButton)
                        .addComponent(seisButton)
                        .addComponent(seteButton)
                        .addComponent(oitoButton)
                        .addComponent(noveButton)
                        .addComponent(cincoButton)
                        .addComponent(okButton)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividirButton)
                    .addComponent(vezesButton)
                    .addComponent(menosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(resultAtualText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zerarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igualButton))
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTextActionPerformed
        
    }//GEN-LAST:event_resultadoTextActionPerformed

    private void maisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisButtonActionPerformed
        operacao = "+";
        String recOP = resultadoText.getText();
        resultadoText.setText(recOP + operacao);
     
    }//GEN-LAST:event_maisButtonActionPerformed

    private void menosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosButtonActionPerformed
        operacao = "-";
        String recOP = resultadoText.getText();
        resultadoText.setText(recOP + operacao);
    }//GEN-LAST:event_menosButtonActionPerformed

    private void vezesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezesButtonActionPerformed
        operacao = "*";
        String recOP = resultadoText.getText();
        resultadoText.setText(recOP + operacao);
    }//GEN-LAST:event_vezesButtonActionPerformed

    private void dividirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirButtonActionPerformed
        operacao = "/";
        String recOP = resultadoText.getText();
        resultadoText.setText(recOP + operacao);
    }//GEN-LAST:event_dividirButtonActionPerformed

    private void igualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualButtonActionPerformed
       
        Double textoAA = Double.parseDouble(textoA);
        resultadoText.setText(String.format("%.1f", textoAA));
       resultAtualText.setText("0");
       
    }//GEN-LAST:event_igualButtonActionPerformed

    private void zerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerarButtonActionPerformed
       operacao = "0";
       textoA = "0";
       textoB = "0";
       resultadoText.setText("0");
       resultAtualText.setText("0");
    }//GEN-LAST:event_zerarButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       String aF1 = floatText.getText();
       boolean resp = Numerico(aF1);
       if(resp == true){
       //StringUtils.isNumeric(aF1);
       double aF2 = Double.parseDouble(aF1);
       if(aF2 < 0.1 && aF2 > -0.1 ){
           JOptionPane.showMessageDialog(null, "Favor inserir um valor diferente de 0");
       }else {
           recebeVal(aF1);
       }
       }else {
           JOptionPane.showMessageDialog(null, "Apenas numeros");
       }
    }//GEN-LAST:event_okButtonActionPerformed

    private void umButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umButtonActionPerformed
       recebeVal("1");
    }//GEN-LAST:event_umButtonActionPerformed

    private void doisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisButtonActionPerformed
        recebeVal("2");
    }//GEN-LAST:event_doisButtonActionPerformed

    private void tresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresButtonActionPerformed
        recebeVal("3");
    }//GEN-LAST:event_tresButtonActionPerformed

    private void quatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroButtonActionPerformed
        recebeVal("4");
    }//GEN-LAST:event_quatroButtonActionPerformed

    private void cincoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoButtonActionPerformed
        recebeVal("5");
    }//GEN-LAST:event_cincoButtonActionPerformed

    private void seisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisButtonActionPerformed
        recebeVal("6");
    }//GEN-LAST:event_seisButtonActionPerformed

    private void seteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteButtonActionPerformed
        recebeVal("7");
    }//GEN-LAST:event_seteButtonActionPerformed

    private void oitoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoButtonActionPerformed
        recebeVal("8");
    }//GEN-LAST:event_oitoButtonActionPerformed

    private void noveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveButtonActionPerformed
        recebeVal("9");
    }//GEN-LAST:event_noveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cincoButton;
    private javax.swing.JButton dividirButton;
    private javax.swing.JButton doisButton;
    private javax.swing.JTextPane floatText;
    private javax.swing.JButton igualButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton maisButton;
    private javax.swing.JButton menosButton;
    private javax.swing.JButton noveButton;
    private javax.swing.JButton oitoButton;
    private javax.swing.JButton okButton;
    private javax.swing.JButton quatroButton;
    private javax.swing.JTextField resultAtualText;
    private javax.swing.JTextField resultadoText;
    private javax.swing.JButton seisButton;
    private javax.swing.JButton seteButton;
    private javax.swing.JButton tresButton;
    private javax.swing.JButton umButton;
    private javax.swing.JButton vezesButton;
    private javax.swing.JButton zerarButton;
    // End of variables declaration//GEN-END:variables
}
